In [17]:
#import utils
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.graphics.mosaicplot import mosaic
import matplotlib as mpl
from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
mpl.rcParams.update(mpl.rcParamsDefault)
plt.rcParams['figure.figsize'] = [4.5, 3.5]

%matplotlib inline
pd.options.display.max_rows = 2000
pd.options.display.max_columns = 100

import warnings
warnings.filterwarnings('ignore')

In [2]:
# https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset

day = pd.read_csv("../datasets/bike_sharing_dataset/day.csv", delimiter=",")
# print first 10 examples
day.head(10)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
5,6,2011-01-06,1,0,1,0,4,1,1,0.204348,0.233209,0.518261,0.089565,88,1518,1606
6,7,2011-01-07,1,0,1,0,5,1,2,0.196522,0.208839,0.498696,0.168726,148,1362,1510
7,8,2011-01-08,1,0,1,0,6,0,2,0.165000,0.162254,0.535833,0.266804,68,891,959
8,9,2011-01-09,1,0,1,0,0,0,1,0.138333,0.116175,0.434167,0.361950,54,768,822
9,10,2011-01-10,1,0,1,0,1,1,1,0.150833,0.150888,0.482917,0.223267,41,1280,1321

In [3]:
# https://archive.ics.uci.edu/dataset/275/bike+sharing+dataset

hour = pd.read_csv("../datasets/bike_sharing_dataset/hour.csv", delimiter=",")
# print first 10 examples
hour.head(10)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
5,6,2011-01-01,1,0,1,5,0,6,0,2,0.24,0.2576,0.75,0.0896,0,1,1
6,7,2011-01-01,1,0,1,6,0,6,0,1,0.22,0.2727,0.80,0.0000,2,0,2
7,8,2011-01-01,1,0,1,7,0,6,0,1,0.20,0.2576,0.86,0.0000,1,2,3
8,9,2011-01-01,1,0,1,8,0,6,0,1,0.24,0.2879,0.75,0.0000,1,7,8
9,10,2011-01-01,1,0,1,9,0,6,0,1,0.32,0.3485,0.76,0.0000,8,6,14

In [11]:
X = hour.loc[:, ["hr"]]
y = hour.loc[:, "cnt"]

# X_train, X_valid, y_train, y_valid = train_test_split(hour, y, test_size=0.3)
# X_train.head()

In [9]:
X.head()

0    0
1    1
2    2
3    3
4    4
Name: hr, dtype: int64

In [45]:
mae = []
n_folds = 10
kf = KFold(n_splits=n_folds)
i = 0
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index, :], X.iloc[test_index, :]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    model = DecisionTreeRegressor()
    model = model.fit(X_train, y_train)
    test_predictions = model.predict(X_test)
    mae.append(mean_absolute_error(y_test, test_predictions))
    print(mae[i])
    i = i + 1
print("Test MAE:", np.mean(mae))

140.61356623708386
73.15110072872511
60.16999476939711
61.07021199976728
79.46359325407397
70.3857773953937
98.33968889464364
117.95638416923613
135.00460104416027
88.13891139344943
Test MAE: 92.42938298859305

In [14]:
def predict(model, X_test, y_test):
    y_pred = model.predict(X_test)
    # print('R2 score:', r2_score(y_test, y_pred))
    # print("root mean_squared_error: ", np.sqrt(mean_squared_error(y_test, y_pred)))
    print("mean_absolute_error: ", mean_absolute_error(y_test, y_pred))
    return y_pred

In [15]:
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.3)

In [43]:
dtr_params ={"splitter":["best", "random"],
            "max_depth":[2, 4, 6, 8, 10, 12, 16],
            "min_samples_leaf":[1, 2, 4, 8],
            "max_features":[2, 4, 8, 12, 16]}

dtr_model = GridSearchCV(
    DecisionTreeRegressor(),
    param_grid=dtr_params,
    scoring="neg_mean_absolute_error",
    cv=10,
    verbose=1,
)

dtr_model.fit(X_train, y_train)

print("Decision Tree best params: \n")
print(dtr_model.best_params_)

print("\n")

print("Decision Tree best score: \n")
print(dtr_model.best_score_)

print("\n")

print("Validation set performance: ")
y_valid_pred_dtr = predict(dtr_model, X_valid, y_valid)

print("\n")

print("Training set performance: ")
y_train_pred_dtr = predict(dtr_model, X_train, y_train)

Fitting 10 folds for each of 280 candidates, totalling 2800 fits
Decision Tree best params:

{'max_depth': 8, 'max_features': 4, 'min_samples_leaf': 2, 'splitter': 'random'}


Decision Tree best score:

-92.52634163547255


Validation set performance:
mean_absolute_error:  87.19160297096467


Training set performance:
mean_absolute_error:  87.90869015622893